### ISSUE TITLE
Cancel Payment Dailog not working properly

### ISSUE THREAD

**Issue by sgrchavan01** [mayurpitroda96/payu_web_checkout#1]

**Comment by mayurpitroda96** [comment]
On which platform?

**Comment by sgrchavan01** [comment]
Dailog not dismiss in android version.
Below code work for me.

showPaymentCancelDialog(BuildContext context) {
    // set up the button
    Widget yesButton = TextButton(
      child: const Text("YES"),
      onPressed: () {
        Navigator.of(context, rootNavigator: true).pop();
        Navigator.pop(context, true);
        widget.onFailed({
          "status": "failure",
          "error_message": "User canceled the payment"
        });
      },
    );

    Widget noButton = TextButton(
      child: const Text("NO"),
      onPressed: () {
        Navigator.of(context, rootNavigator: true).pop();
      },
    );

    // set up the AlertDialog
    AlertDialog alert = AlertDialog(
      title: Row(
        children: const [
          Text("Exiting payment"),
        ],
      ),
      content: const Text("Are you sure you want to exit payment?"),
      actions: [noButton, yesButton],
    );

    // show the dialog
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return alert;
      },
    );
  }

**Comment by mayurpitroda96** [comment]
android version?

**Comment by sgrchavan01** [comment]
Android Version 9
Redmi Note 5 Pro

**Comment by mayurpitroda96** [comment]
Ok, I will check in android version 9 if any problem I will fix and update the pub.

**Comment by mayurpitroda96** [comment]
https://user-images.githubusercontent.com/91420335/152141052-d8a2933e-5d7d-461c-a4f1-a2c55730c587.mov

Working fine in android version 9.
