### ISSUE TITLE
After success the payment success handler not triggering

### ISSUE THREAD

**Issue by buddhabalamurali** [mayurpitroda96/payu_web_checkout#2]
I am using this Library for implement payu money all payment process run smoothly but after Complete payment the respective handler not triggering once check this scenario

**Comment by mayurpitroda96** [comment]
Have you host the file payu_success.php and payu_failed.php?

**Comment by buddhabalamurali** [comment]
No I am not host those files to server after success handler will trigger to success handler,  i am send those information to server to update.
Server side they using  .net Not php after complete payment close the view and return success data to handler i wiil handle remain process

**Comment by mayurpitroda96** [comment]
Have you created success and failed endpoint in .net?

**Comment by buddhabalamurali** [comment]
no

**Comment by buddhabalamurali** [comment]
I am implement in this for mobile android and Ios platforms so web view return to app and success handle trigger I will call API in that point.

**Comment by mayurpitroda96** [comment]
so create success and failed endpoint set in 

successUrl: "https://payu.mayurpitroda.com/payu_success.php",
failedUrl: "https://payu.mayurpitroda.com/payu_failed.php",

after success and failure trigger will be called.

**Comment by buddhabalamurali** [comment]
can I use above Urls for my end points then it will trigger

**Comment by mayurpitroda96** [comment]
No, because my endpoints sometimes do not work. so you will create your own endpoints.
dm in skype -> mayurpitroda

**Comment by buddhabalamurali** [comment]
ok once i will update server side people tq for your support u save my day.
